# Generated by Django 3.2 on 2022-02-23 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220223_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderdetail',
            name='sale_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.saleorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'initial'), (1, 'wating approved'), (2, 'on going'), (3, 'done'), (4, 'failed')], default=0),
        ),
    ]
