# Generated by Django 3.2 on 2022-05-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_saleorder_custom_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderdetail',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='deposite_type',
            field=models.IntegerField(blank=True, choices=[(3, 'Please select a choice'), (0, 'percentage'), (1, 'amount')], null=True),
        ),
    ]
