# Generated by Django 3.2 on 2022-06-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220519_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorderdetail',
            name='color_id',
        ),
        migrations.AddField(
            model_name='saleorderdetail',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
