# Generated by Django 3.2 on 2022-06-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220606_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemColor',
        ),
    ]
