# Generated by Django 2.2.10 on 2022-03-08 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220308_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorder',
            old_name='delivery_date',
            new_name='delivery_date_end_date',
        ),
        migrations.AddField(
            model_name='saleorder',
            name='delivery_date_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
