# Generated by Django 2.2.10 on 2022-03-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220308_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorder',
            old_name='delivery_date_end_date',
            new_name='delivery_end_date',
        ),
        migrations.RenameField(
            model_name='saleorder',
            old_name='delivery_date_start_date',
            new_name='delivery_start_date',
        ),
    ]
