# Generated by Django 2.2.10 on 2022-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220308_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderdetail',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
