# Generated by Django 3.2 on 2022-03-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220314_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='signature_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
