# Generated by Django 3.2 on 2022-02-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentlog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departmentlog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
